# Sample Prometheus Alert Rules for Social Suit and Sparkr Backend

groups:
  - name: api_alerts
    rules:
      # High Error Rate Alert
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status_code=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High HTTP error rate detected"
          description: "Error rate is above 5% for the last 2 minutes ({{ $value | printf \"%.2f%%\" }})"

      # Slow Response Time Alert
      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service)) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow response time detected"
          description: "95th percentile of HTTP response time is above 2 seconds for the last 5 minutes"

      # High API Rate Limit Hits
      - alert: HighRateLimitHits
        expr: sum(rate(api_rate_limit_hits_total[5m])) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High rate limit hits detected"
          description: "More than 10 rate limit hits per second for the last 5 minutes"

      # Database Query Duration Alert
      - alert: SlowDatabaseQueries
        expr: histogram_quantile(0.95, sum(rate(db_query_duration_seconds_bucket[5m])) by (le, query_type)) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "95th percentile of database query duration is above 1 second for the last 5 minutes"

  # Social Suit specific alerts
  - name: social_suit_alerts
    rules:
      # Social API Error Rate Alert
      - alert: SocialAPIHighErrorRate
        expr: sum(rate(social_api_requests_total{status="error"}[5m])) / sum(rate(social_api_requests_total[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High social API error rate detected"
          description: "Social API error rate is above 10% for the last 5 minutes ({{ $value | printf \"%.2f%%\" }})"

      # Slow Social API Response Time
      - alert: SlowSocialAPIResponseTime
        expr: histogram_quantile(0.95, sum(rate(social_api_request_duration_seconds_bucket[5m])) by (le, platform)) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow social API response time detected"
          description: "95th percentile of social API response time is above 5 seconds for the last 5 minutes"

  # Sparkr Backend specific alerts
  - name: sparkr_alerts
    rules:
      # High Submission Failure Rate
      - alert: HighSubmissionFailureRate
        expr: sum(rate(submissions_total{status="failed"}[5m])) / sum(rate(submissions_total[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High submission failure rate detected"
          description: "Submission failure rate is above 5% for the last 5 minutes ({{ $value | printf \"%.2f%%\" }})"

  # System resource alerts (applicable to both projects)
  - name: resource_alerts
    rules:
      # High CPU Usage
      - alert: HighCPUUsage
        expr: process_cpu_seconds_total / on(instance) group_left() machine_cpu_cores > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for the last 5 minutes"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / on(instance) group_left() machine_memory_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 80% for the last 5 minutes"

      # Instance Down
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance down"
          description: "Instance {{ $labels.instance }} has been down for more than 1 minute"